let products=[
  {"id":"ma5500ifx","marca":"KYOCERA","modelo":"MA5500ifx","tipo":"Multifuncional monocromática","frase":"Potencia y velocidad para oficinas exigentes.","ext":"png","frames":1,"caracteristicas":["57 ppm","Impresión, copia, escaneo y fax","Pantalla táctil 7\"","Dúplex automático","ADF dúplex","Red Gigabit","Impresión móvil","Alto ciclo mensual"]},
  {"id":"ma4500ifx","marca":"KYOCERA","modelo":"MA4500ifx","tipo":"Multifuncional monocromática","frase":"Productividad confiable para grupos de trabajo.","ext":"png","frames":1,"caracteristicas":["47 ppm","Impresión, copia, escaneo y fax","Pantalla táctil","Dúplex automático","ADF","Red Gigabit","Impresión móvil","Seguridad empresarial"]},
  {"id":"ma4000xl","marca":"KYOCERA","modelo":"MA4000X/L","tipo":"Multifuncional monocromática","frase":"Rendimiento compacto para oficina moderna.","caracteristicas":["40 ppm","Multifuncional","Dúplex automático","Alta eficiencia","Red","Bajo costo operativo","Diseño compacto","Ideal para oficina"]},
  {"id":"pa5000x","marca":"KYOCERA","modelo":"PA5000X","tipo":"Impresora monocromática","frase":"Velocidad y durabilidad para impresión diaria.","caracteristicas":["50 ppm","Impresión monocromática","Dúplex automático","Red Gigabit","Alta capacidad","Equipo robusto","Bajo consumo","Alta productividad"]},
  {"id":"brother-mfc-j6975dw","marca":"BROTHER","modelo":"MFC-J6975DW","tipo":"Multifuncional color","frase":"Impresión versátil para documentos de gran formato.","caracteristicas":["Color","Multifuncional","Impresión A3","Escaneo A3","Dúplex","Wi‑Fi","Pantalla táctil","Ideal para oficina"]},
  {"id":"bizhub-c301i","marca":"KONICA MINOLTA","modelo":"Bizhub C301i","tipo":"Multifuncional color","frase":"Color profesional con experiencia intuitiva.","ext":"png","frames":1,"caracteristicas":["Color","30 ppm","Multifuncional","Pantalla táctil","Dúplex automático","Red","Seguridad avanzada","Alta calidad"]},
  {"id":"bizhub-c361i","marca":"KONICA MINOLTA","modelo":"Bizhub C361i","tipo":"Multifuncional color","frase":"Mayor velocidad para entornos exigentes.","ext":"png","frames":1,"caracteristicas":["Color","36 ppm","Multifuncional","Pantalla táctil","Dúplex automático","Red","Seguridad avanzada","Alta productividad"]},
  {"id":"taskalfa-mz4001i","marca":"KYOCERA","modelo":"TASKalfa MZ4001i","tipo":"Multifuncional monocromática","frase":"Solución robusta para alto volumen documental.","caracteristicas":["40 ppm","Multifuncional","Pantalla táctil","Dúplex automático","ADF","Red","Alta durabilidad","Trabajo intensivo"]},
  {"id":"epson-wf-c5891","marca":"EPSON","modelo":"WF-C5891","tipo":"Multifuncional color","frase":"Color eficiente con tecnología de inyección profesional.","caracteristicas":["Color","Multifuncional","Dúplex automático","Wi‑Fi / Red","Bajo consumo","Impresión móvil","Compacta","Oficina eficiente"]}
]
, current=0, frame=1, zoom=1, dragging=false, startX=0, autoTimer=null;
const app=document.getElementById('app');
function frameCount(){return products[current]?.frames || 24}
routeHome();
function imgPath(p,n=1){return `img/productos/${p.id}/${String(n).padStart(2,'0')}.${p.ext || 'jpg'}`}
function fallback(e){e.target.src='img/productos/placeholder.svg'}
function routeHome(){clearInterval(autoTimer);app.innerHTML=`<main class="wrap"><div class="top"><img class="logo" src="img/logo-grupo-printer.png"><span class="pill">Offline Showcase</span></div><section class="hero"><h1>Catálogo Interactivo</h1><p>Soluciones de impresión para presentar desde tu iPad.</p></section><section class="grid">${products.map((p,i)=>`<button class="card" onclick="routeProduct(${i})"><img src="${imgPath(p,1)}" onerror="fallback(event)"><div class="brand">${p.marca}</div><div class="model">${p.modelo}</div><div class="type">${p.tipo}</div></button>`).join('')}</section></main>`}
function routeProduct(i){current=i; frame=1; zoom=1; const p=products[i];app.innerHTML=`<main class="wrap"><div class="top"><img class="logo" src="img/logo-grupo-printer.png"><button class="back" onclick="routeHome()">Inicio</button></div><section class="productHead"><div class="brand">${p.marca}</div><h1>${p.modelo}</h1><div class="type">${p.tipo}</div><p class="phrase">${p.frase}</p></section><section class="viewer" id="viewer"><img id="productImg" src="${imgPath(p,1)}" onerror="fallback(event)"></section><div class="hint">Gira con tu dedo • Pellizca para zoom • Rota automáticamente</div><section class="features"><h2>Características principales</h2><div class="featureGrid">${p.caracteristicas.map(x=>`<div class="feature"><b>${x}</b></div>`).join('')}</div></section></main><div class="nav"><button class="ghost" onclick="routeProduct((current-1+products.length)%products.length)">Anterior</button><button onclick="routeHome()">Inicio</button><button class="ghost" onclick="routeProduct((current+1)%products.length)">Siguiente</button></div>`; bindViewer(); startAuto();}
function updateImg(){const p=products[current], img=document.getElementById('productImg'); if(!img)return; img.src=imgPath(p,frame); img.style.transform=`scale(${zoom})`;}
function startAuto(){clearInterval(autoTimer); const total=frameCount(); if(total<=1)return; autoTimer=setInterval(()=>{frame=frame%total+1; updateImg();},160)}
function bindViewer(){const v=document.getElementById('viewer'); v.addEventListener('pointerdown',e=>{dragging=true;startX=e.clientX;clearInterval(autoTimer);v.setPointerCapture(e.pointerId)});v.addEventListener('pointermove',e=>{if(!dragging)return;const dx=e.clientX-startX;if(Math.abs(dx)>12){frame=((frame+(dx<0?1:-1)-1+frameCount())%frameCount())+1;startX=e.clientX;updateImg();}});v.addEventListener('pointerup',()=>{dragging=false;startAuto()});v.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.min(2.4,Math.max(1,zoom+(e.deltaY<0?.08:-.08)));updateImg();},{passive:false});let lastDist=0;v.addEventListener('touchmove',e=>{if(e.touches.length===2){e.preventDefault();const a=e.touches[0],b=e.touches[1],d=Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY);if(lastDist){zoom=Math.min(2.4,Math.max(1,zoom+(d-lastDist)/350));updateImg()}lastDist=d;}},{passive:false});v.addEventListener('touchend',()=>lastDist=0)}
